server:
  port: 8862
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka
spring:
  application:
    name: eureka-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
base-path: /
