spring:
  redis:
    host: 127.0.0.1  # Redis服务器地址
    jedis:
      pool:
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8  # 连接池中的最大空闲连接
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
    port: 6379
    database: 0   # Redis数据库索引（默认为0）
    timeout:  0  # 连接超时时间（毫秒）



